### ISSUE TITLE
Getting error on Forget Password action

### ISSUE THREAD

**Issue by durgaganesh** [hungdev/react-native-instagram-login#11]
When I click on "Forget Password" link, I am getting error screen as I attached in my Android emulator. Could you please check it
![screen shot 2018-05-02 at 5 22 16 pm](https://user-images.githubusercontent.com/2277554/39529353-15f2b692-4e44-11e8-94d3-48e39915fbab.png)

**Comment by hungdev** [comment]
i run still fine. Could you give me your code?

**Comment by nihp** [comment]
@hungdev I am getting the same error when I click on the "Forgot Password" in my iPhone7 plus simulator. 

![screen shot 2018-05-04 at 4 32 43 pm](https://user-images.githubusercontent.com/36992338/39626471-a0dab5da-4fbf-11e8-88b9-7028e956cac4.png)

**Comment by hungdev** [comment]
@nihp  please install the last version.

**Comment by nihp** [comment]
@hungdev I have installed latest version package of "react-native-instagram-login@1.0.6". But it does not resolved yet

**Comment by hungdev** [comment]
@nihp  remove node_modules then reinstall.

**Comment by hungdev** [comment]
@nihp  everything ok?

**Comment by nihp** [comment]
@hungdev No, It does not resolved. I removed the node_modules and reinstalled. But it not worked in simulator

**Comment by hungdev** [comment]
updated. please try again.
