### ISSUE TITLE
Implicit authentication is disabled

### ISSUE THREAD

**Issue by Ilario17** [hungdev/react-native-instagram-login#12]
this is my Component:

<InstagramLogin
	ref='instagramLogin'
        clientId='eeeee'
	redirectUrl='eee'
	scopes={['basic']}
	onLoginSuccess={(token) => console.log(token)}
	onLoginFailure={(data) => console.log(data)}
/>

**Comment by hungdev** [comment]
could you give me the capture?

**Comment by hungdev** [comment]
try this
https://stackoverflow.com/questions/30322694/instagram-error-implicit-authentication-is-disabled

**Comment by Ilario17** [comment]
![simulator screen shot - iphone 6 - 2018-05-08 at 12 14 49](https://user-images.githubusercontent.com/33326791/39751769-821390ca-52b9-11e8-9436-01d350a7d2c1.png)
