### ISSUE TITLE
signup with instagram working on amulator debug mode but not working when I close debuger

### ISSUE THREAD

**Issue by junaid-junnu** [hungdev/react-native-instagram-login#121]
Hi
 I add this package it works on the emulator during debug time but not working when the debugger is closed or when making a build .
 
Does anyone have an idea about how to do that?

Thank you

**Comment by Jaredude** [comment]
This sounds like the same bug as here: https://github.com/hungdev/react-native-instagram-login/issues/120 solution is to add explicit withCredentials: false to the axis call

**Comment by junaid-junnu** [comment]
@Jaredude Thanks.
its worked.
