### ISSUE TITLE
Chỉ login được với tài khoản dùng để đăng kí client id

### ISSUE THREAD

**Issue by thangkho** [hungdev/react-native-instagram-login#13]
Khi mình dùng ex của bạn để login( đã thay client id... bằng id của mình) nhưng khi login nó chỉ login được với tài khoản dùng để đăng ký client id.. còn với tài khoản khác thì hiện lỗi : you are not a sandbox user or this client.
Mong bác giúp mình khắc phục lỗi này với

**Comment by hungdev** [comment]
bạn phải add nó vô sanbox user.

**Comment by hungdev** [comment]
đúng rồi bạn.

**Comment by roulydev** [comment]
e chào bác! hnay instagram nó mới duyệt app cho để login vs email khác...
Nhưng hiện tại khi login thì nó hiện thị lỗi `{"error_type" : "OAuthException" , "code" : 400 , "error_message" : " Redirect URI dose not match registered redirect URI"}` 
E không hiểu rõ lăm về  `Valid redirect URIs` trong setting. Url như thế nào thì mới hợp lệ ạ?
Mong bác giúp đỡ.

**Comment by hungdev** [comment]
cái domain rederect trong code với cái domain đăng ký trong  https://www.instagram.com/developer/ phải giống nhau bạn.

**Comment by thangkho** [comment]
Còn nó không yêu cầu gì về url đó phải không bcá? E dẫn đên link website công ty cũng ok nhỉ?
