### ISSUE TITLE
How is supposed to work?

### ISSUE THREAD

**Issue by Solitaryo** [hungdev/react-native-instagram-login#18]
I can't make it work at all.
The modal appears, put the info, and it just give me lots of promises warnings, but that's all, it does nothing, doesn't return a token or any kind of data.
And after you login, the only thing you get is your instagram page, but no token, no nothing.

I'm using Macbook pro, OSX 10.13.6.
Node version 10.10.0
"react": "16.4.1",
"react-native": "0.56.0",
"react-native-instagram-login": "1.0.7",

**Comment by hungdev** [comment]
Have you changed client id and set up it in  
https://www.instagram.com/developer/register/ yet?
