### ISSUE TITLE
new instagram interface for login  not responding 

### ISSUE THREAD

**Issue by hagar0459** [hungdev/react-native-instagram-login#19]
i followed Instagram login example and replaced the xxxx with my client id but the web view is responding very badly either to enter username and password or to hit the login button

**Comment by ayberkanilatsiz** [comment]
same +1

**Comment by ayberkanilatsiz** [comment]
@hagar0459 https://github.com/hungdev/react-native-instagram-login/pull/20

i send pull request it works fine.

**Comment by hungdev** [comment]
I tried with the example. It still runs fine. Please check your setup in: https://www.instagram.com/developer/

**Comment by nicolasnsosa** [comment]
Hi Hungdev,

Sorry, I know is this not the thread but I want to know if you have information about review times for a new client app on Instagram. The plugin works perfect but I have stuck on Instagram review process.

Thank you so much.

**Comment by sandy428** [comment]
I am still seeing the error even with the Example and the client Id inside the example.
OS Version  - Android 8.1

**Comment by hungdev** [comment]
I just updated a bit. if guys still get the error, please comment here, I will reopen the issue and try to fix it. thanks!
