### ISSUE TITLE
How do you logout?

### ISSUE THREAD

**Issue by bispul** [hungdev/react-native-instagram-login#2]
I tried the logging out as said in the documentation but got undefined is not an object (evaluating 'CookieManager.clearCookies'). I have attached the screenshot. Can anyone please help me with this?
![screen shot 2017-10-09 at 5 54 57 pm](https://user-images.githubusercontent.com/11752864/31361869-45468d80-ad1b-11e7-8c87-2270f9243965.png)

**Comment by hungdev** [comment]
are you try with example?

**Comment by brkrtp** [comment]
+1 Same

**Comment by bispul** [comment]
ohh thanks @brkrtp
