### ISSUE TITLE
Webview always logged.

### ISSUE THREAD

**Issue by warlock** [hungdev/react-native-instagram-login#22]
I would like to be able to log out and log back in with another user.
It seems that webview remember login.

Any ideas?
Thank you!

**Comment by hungdev** [comment]
https://github.com/hungdev/react-native-instagram-login#logout

**Comment by warlock** [comment]
Yes, sorry i forgot comment. react-native-cookie not working for me. :(
I'm usign Expo. Maybe it's a problem?

**Comment by hungdev** [comment]
you can try with https://github.com/joeferraro/react-native-cookies to clear cookie

**Comment by warlock** [comment]
Thank you. I have problems linking in expo. Later try and send the comment.
