### ISSUE TITLE
Redirect issue - Instagram login issue in 'Suspicious Login Attempt' flow

### ISSUE THREAD

**Issue by sujay-bidchat** [hungdev/react-native-instagram-login#24]
@hungdev @euharrison @santiagofm @areazus While trying to sign in sometimes **Suspicious Login Attempt** screen is shown where we can enter security code. After successfully entering the code it is redirected to Instagram home screen (www.instagram.com) instead of our **redirect_uri** which we pass.

**Comment by hungdev** [comment]
After redirecting to Instagram, if you turn off the modal and log in again,it will display authentication as usual.
I am relying on the results returned to catch webview reload. But the results are not very different.
Do you have any ideas?
![rd](https://user-images.githubusercontent.com/12009276/51622668-9f879200-1f69-11e9-8ca3-9aafc8e5754f.png)

**Comment by hungdev** [comment]
@sujay-bidchat
I fixed this bug and create a new release version. please remove the old version and reinstall new version 1.1.0.
If you still get this error, please comment and tag me here.

**Comment by sujay-bidchat** [comment]
@hungdev thanks for the response. I've put a temporary fix. I check if the url is www.instagram.com and remove the webview and add it again. This solved the problem.

**Comment by hungdev** [comment]
yeah, I do the same as you @sujay-bidchat

**Comment by salmanbukharihitori** [comment]
Hi I am still having this issue. Users get stuck in endless loop of security code authentication. Can you please help?

**Comment by peachlsy** [comment]
Hi, 

I'm facing this issue as well.

RN: 0.59.8
 "react-native-instagram-login": "^1.1.1"

Please advice me what to do, thank you very much!

**Comment by salmanbukharihitori** [comment]
Hi @peachlsy the above solution should work in addition also make sure you do not clear any cookies on webview.

**Comment by iluvhk3000** [comment]
I have the same issue too

**Comment by iluvhk3000** [comment]
@hungdev Could you please check is this issue happened again? Thanks a lot!
