### ISSUE TITLE
App redirect user to "redirectUrl"

### ISSUE THREAD

**Issue by bharatidudhjiya** [hungdev/react-native-instagram-login#25]
I am using this library with react native 0.57.3 but it redirect user to "redirectUrl",  in my case it  is redirecting user to "google.com" url which is my redirect url.

please any one can help me to solve this issue.

Thanks!

**Comment by filipeisho** [comment]
You need to setup your redirect url inside the instagramLogin component :)
```
<InstagramLogin
        ref= {ref => this.instagramLogin= ref}
        clientId='xxxxxx'
        redirectUrl='redirecUrl'
        scopes={['public_content', 'follower_list']}
        onLoginSuccess={(token) => this.setState({ token })}
        onLoginFailure={(data) => console.log(data)}
    />
```

**Comment by hungdev** [comment]
@bharatidudhjiya please read example.
https://github.com/hungdev/react-native-instagram-login/blob/master/Example/App.js#L51-L58

**Comment by IcebergRage** [comment]
@bharatidudhrejiya Did you find a solution ?
On iOS it works but on Android, the redirection is made on my redirect_uri (https://google.com)
I don't understand why...

**Comment by IcebergRage** [comment]
Ok, got it.
It's look like on android, google.com it's automatically turn into www.google.com and doesn't match with `this.props.redirectUrl` !
I add into instagram.js, line 52 : `if (url && url.startsWith(this.props.redirectUrl) || url && url.startsWith('https://www.google.com/')) {`
