### ISSUE TITLE
no response when completed

### ISSUE THREAD

**Issue by VolckaertAchiel** [hungdev/react-native-instagram-login#27]
i have the code below, like the example. it does not log anything after redirect?

        <View>
            <TouchableOpacity onPress={()=> this.instagramLogin.show()}>
                <Text style={{color: 'black', margin: '20%'}}>Login</Text>
            </TouchableOpacity>
            <InstagramLogin
                ref= {ref => this.instagramLogin= ref}
                responseType="token"
                clientId=''
                scopes={['public_content', 'follower_list']}
                onLoginSuccess={(token) => console.log(token)}
                onLoginFailure={(data) => console.log(data)}
                onClose={(data) => console.log(data)}
                redirectUrl="https://us-central1-scautapp.cloudfunctions.net/url_get&response_type=token"
            />
        </View>

**Comment by hungdev** [comment]
@VolckaertAchiel 
The redirectUrl must be the same with  redirect URIs in tab Security  https://www.instagram.com/developer/clients/
Please make sure that every props value are correct.
And final, please give me a video of bug.

**Comment by VolckaertAchiel** [comment]
@hungdev the code is correct, just onloginsucces isn't executed

**Comment by hungdev** [comment]
@VolckaertAchiel 
could you give me an example on https://snack.expo.io
I will check for you.

**Comment by VolckaertAchiel** [comment]
i'm not able to create a snack.

this is the only code in my component, it loads fine, i can login with a registered sandboxuser and it redirect to my url i defined. when it reaches that expect that i should get my token? it logs nothing, is not even executed, the log on close logs something but has no data, which is expected.

i kinda really need the token 😄 

View>
            <TouchableOpacity onPress={()=> this.instagramLogin.show()}>
                <Text style={{color: 'black', margin: '20%'}}>Login</Text>
            </TouchableOpacity>
            <InstagramLogin
                ref= {ref => this.instagramLogin= ref}
                responseType="token"
                clientId='bf9737446be74e7c8ddaea820a242f3a'
                scopes={['public_content', 'follower_list']}
                onLoginSuccess={(token) => console.log('token: '+token)}
                onLoginFailure={(data) => console.log('error: '+data)}
                onClose={(data) => console.log("close")}
                redirectUrl="https://us-central1-scautapp.cloudfunctions.net/url_get&response_type=token"
            />
        </View>

**Comment by VolckaertAchiel** [comment]
i'm not able to create a snack.

this is the only code in my component, it loads fine, i can login with a registered sandboxuser and it redirect to my url i defined. when it reaches that expect that i should get my token? it logs nothing, is not even executed, the log on close logs something but has no data, which is expected.

yes my client id is filled in

i kinda really need the token 😄

View>
<TouchableOpacity onPress={()=> this.instagramLogin.show()}>
<Text style={{color: 'black', margin: '20%'}}>Login

<InstagramLogin
ref= {ref => this.instagramLogin= ref}
responseType="token"
clientId=''
scopes={['public_content', 'follower_list']}
onLoginSuccess={(token) => console.log('token: '+token)}
onLoginFailure={(data) => console.log('error: '+data)}
onClose={(data) => console.log("close")}
redirectUrl="https://us-central1-scautapp.cloudfunctions.net/url_get&response_type=token"
/>

**Comment by hungdev** [comment]
Could you give me a recorded video?

**Comment by VolckaertAchiel** [comment]
![image](https://user-images.githubusercontent.com/26697855/52626095-c115d280-2eb2-11e9-9bca-e40c3a933999.png)

![ezgif com-optimize](https://user-images.githubusercontent.com/26697855/52626328-3ed9de00-2eb3-11e9-9d40-4bf0cacb4a72.gif)

**Comment by hungdev** [comment]
@VolckaertAchiel 
I know what the reason is. Webview response has been changed. and <WebView/> is going to be removed from the React Native core. So I decided to use react-native-webview as react native team suggests.
I release 1.1.0 version. Please reinstall lib, and follow the instructions in the readme.
Feel free to reply if the issue still exists.
see more:
https://facebook.github.io/react-native/docs/webview
https://github.com/react-native-community/discussions-and-proposals/issues/6
