### ISSUE TITLE
doesn't work with expo any more

### ISSUE THREAD

**Issue by jkmf** [hungdev/react-native-instagram-login#29]
Since last commit Expo compatibility has been broken. 
Expo developers can't do: react-native link react-native-webview

> Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

**Comment by hungdev** [comment]
React Native WebView is not currently supported by Expo unless you "eject".
https://github.com/react-native-community/react-native-webview#platforms-supported

**Comment by hungdev** [comment]
you can install 1.1.0 version and add `www` in redirectUrl ( both redirectUrl props and https://www.instagram.com/developer/clients/

```
<Ins
          ref='ins'
          clientId=''
          redirectUrl='https://www.google.com'   // <=======like this
          scopes={['public_content+follower_list']}
          onLoginSuccess={(token) => this.setState({ token })}
          onLoginFailure={(data) => this.setState({ failure: data })}
```
https://github.com/hungdev/react-native-instagram-login/issues/27#issuecomment-462848799

**Comment by hungdev** [comment]
Note: Expo support for React Native WebView started with Expo SDK v33.0.0.
https://github.com/react-native-community/react-native-webview#platforms-supported
