### ISSUE TITLE
Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by marcoizzo** [hungdev/react-native-instagram-login#3]
After install and import I get this error:

<img width="374" alt="schermata 2017-10-10 alle 13 48 03" src="https://user-images.githubusercontent.com/13518657/31385099-161ae96e-adc2-11e7-8ba2-b8f48ea3f28d.png">

I use `import InstagramLogin from 'react-native-instagram-login'`
React versione: 0.49.3

Thanks

**Comment by hungdev** [comment]
thank for report. this issue fixed. please check it again.

**Comment by marcoizzo** [comment]
It works! Thank you!
