### ISSUE TITLE
Unable to login via instagram

### ISSUE THREAD

**Issue by nihp** [hungdev/react-native-instagram-login#31]
I am trying to login my app via Instagram. But it showing the error as 
![Screenshot 2019-04-01 at 9 35 03 AM](https://user-images.githubusercontent.com/36992338/55303023-89161f00-5461-11e9-8655-952b1129d277.png)

**Comment by hungdev** [comment]
@nihp  have you link `react-native link react-native-webview`?

**Comment by nihp** [comment]
Now I have linked the react-native-webview. Still facing the same issue.  Is it show in libraries after linking it?

**Comment by hungdev** [comment]
@nihp hi guy, I tried it again and I found everything was okay.

**Comment by hungdev** [comment]
here is my record video: https://youtu.be/rKc90_DOIZ8

**Comment by nihp** [comment]
Thanks @hungdev

**Comment by hungdev** [comment]
@nihp You have successfully installed it ?

**Comment by nihp** [comment]
Not yet I am checking this issue

**Comment by hungdev** [comment]
@nihp everything fine?

**Comment by nihp** [comment]
No I am facing the same issue. I didn't found any solution for this

**Comment by hungdev** [comment]
@nihp are you try with creating a new example?

**Comment by nihp** [comment]
Yes, I have installed my app newly in separate folder and trying to login

Note: It worked previously (i.e) before one week

**Comment by hungdev** [comment]
please create new project and setup with last version react native instagram and record the video. You can send your video to my mail if it is a video with a sensitive key. @nihp

**Comment by nihp** [comment]
I am not tried with a new demo. But I am facing an error as "InvariantViolation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager"

![Screenshot 2019-04-04 at 3 43 30 PM](https://user-images.githubusercontent.com/36992338/55549132-ccd38780-56f2-11e9-8dc7-be26aff6d809.png)

**Comment by hungdev** [comment]
Remove your project and create and resetup again.

**Comment by nihp** [comment]
Fixed the above issue by adding RNCWebview in my Link binaries.

Thanks @hungdev
