### ISSUE TITLE
Android can't login 

### ISSUE THREAD

**Issue by zaakzaku** [hungdev/react-native-instagram-login#32]
when i was login after redirect google.com

**Comment by hungdev** [comment]
@zaakzaku 
change your redirectUrl in your code and in the web https://www.instagram.com/developer/clients/

**Comment by zaakzaku** [comment]
i'm using 1.1.0

**Comment by hungdev** [comment]
@zaakzaku yeah. please remove node_modules and reinstall last version:
npm install react-native-instagram-login@1.1.1 --save

**Comment by zaakzaku** [comment]
okay thanks.

**Comment by hungdev** [comment]
Feel free to let me know if the issue still exists

**Comment by zaakzaku** [comment]
> Feel free to let me know if the issue still exists

reinstall last version. it's fixed  @hungdev thanks
