### ISSUE TITLE
How to get name or avatar url after login?

### ISSUE THREAD

**Issue by xfishernet** [hungdev/react-native-instagram-login#33]
How to get name or avatar url after login?

**Comment by hungdev** [comment]
@xfishernet 
after get token, you can use this api: `https://api.instagram.com/v1/users/self/?access_token=ACCESS-TOKEN`

please read here to get more information: https://www.instagram.com/developer/endpoints/users/#get_users_self

**Comment by xfishernet** [comment]
thanks!
