### ISSUE TITLE
Android can't login webview modal redirect to browser

### ISSUE THREAD

**Issue by zaakzaku** [hungdev/react-native-instagram-login#34]
Help me

**Comment by hungdev** [comment]
please read this [issue](https://github.com/hungdev/react-native-instagram-login/issues/32)

**Comment by hungdev** [comment]
please give me your code and react-native-instagram-login version.

**Comment by zaakzaku** [comment]
it's last version 1.1.1 can u try it android?
![Capture111](https://user-images.githubusercontent.com/23735741/56405592-84de6400-629f-11e9-8afa-5204def1c628.PNG)

**Comment by hungdev** [comment]
add your redirectUrl props like this: https://github.com/hungdev/react-native-instagram-login/blob/master/Example/App.js#L54

**Comment by zaakzaku** [comment]
i just add redirect url but it's not fixed. when i login button click opened web browser
![Capture22](https://user-images.githubusercontent.com/23735741/56405890-0da9cf80-62a1-11e9-95ec-3e7652c8b323.PNG)

**Comment by hungdev** [comment]
I will try it on android afternoon.

**Comment by zaakzaku** [comment]
okay thank u

**Comment by hungdev** [comment]
@zaakzaku i tried it on android device and everything is oke. 
you can see setup video on ios. it like on android.

**Comment by hungdev** [comment]
@zaakzaku every thing oke?

**Comment by zaakzaku** [comment]
please check it https://play.google.com/store/apps/details?id=com.zu_club

**Comment by hungdev** [comment]
@zaakzaku sorry to late reply. If you don't mind, I can talk to you via mail and support you with teamview

**Comment by zaakzaku** [comment]
okay thank u. i will send you email :)

**Comment by hapSa000** [comment]
I am also facing same error and  in the video there I nothing about web view I
![Screenshot (137)](https://user-images.githubusercontent.com/46805839/61115407-0107d280-a4b0-11e9-88a4-d4442e903c95.png)
 want to make this for android

**Comment by hungdev** [comment]
@hapSa000 did you link react-native-webview ?
this problem related webview, you can find the issue at https://github.com/react-native-community/react-native-webview/issues

**Comment by hapSa000** [comment]
> @hapSa000 did you link react-native-webview ?
> this problem related webview, you can find the issue at https://github.com/react-native-community/react-native-webview/issues

yes I did link react-native-webview
and I'm using latest react-native version 0.60 which autolink native dependencies

**Comment by hungdev** [comment]
@hapSa000 remove node_module and reinstall react-native-webview. if it still errors, you can find the issue at https://github.com/react-native-community/react-native-webview/issues
