### ISSUE TITLE
Error Compile react-native run-android

### ISSUE THREAD

**Issue by wibav** [hungdev/react-native-instagram-login#35]
when i run-android give this error

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring project ':react-native-webview'.
> > Could not resolve all artifacts for configuration ':react-native-webview:classpath'.
>    > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11.
>      Required by:
>          project :react-native-webview
>       > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.11.
>          > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom'.
>             > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.11/kotlin-gradle-plugin-1.3.11.pom'.
>                > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

package.json
 "dependencies": {
    "axios": "^0.19.0",
    "react": "16.8.3",
    "react-native": "0.59.3",
    "react-native-elements": "^1.1.0",
    "react-native-instagram-login": "^1.1.1",
    "react-native-vector-icons": "^6.0.0",
    "react-navigation": "^2.11.2"
}

**Comment by hungdev** [comment]
due to react native webview, please reinstall lib.
