### ISSUE TITLE
Webview don't display Instagram Login Page at the second Longin attempt.

### ISSUE THREAD

**Issue by jinguohao1991** [hungdev/react-native-instagram-login#36]
Hi, Thank you for your effort with stuff.
I am building iOS app with ReactNative 0.59.8.
The Instagram login component works fine and shows the Login page on webview successfully.
But the problem is here.
I failed to login due to the redirect_url issue, so I closed modal and tried again.
But the web view didn't show the login page, showed only loading spinner image.
In order to log in again, I had to uninstall the app from the device.
I want to know what the cause was.
Hope to be fixed asap if this is an issue.
Thank you.

**Comment by hungdev** [comment]
@jinguohao1991 can you give me a video about this bug? I will fix it soon if the error is determined.

**Comment by hungdev** [comment]
it duplicate with issue https://github.com/hungdev/react-native-instagram-login/issues/37
