### ISSUE TITLE
I cannot change Instagram Login account after login

### ISSUE THREAD

**Issue by jinguohao1991** [hungdev/react-native-instagram-login#37]
Hi, Thank you for your effort with this package.
It helped me much with my work for instagram login.
But I have found an issue on webview.
The webview in the modal works fine at the first login.
But after login successfully, if I try to use another account to login, webview doesn't show the Instagram Login page.
So I cannot change to another account.
As I checked the code there was a code block to change `key` which is responsible for refreshing webview.
But it doesn't work properly. This is the code.
... .... ...
    const { url } = webViewState
    const { key } = this.state
    if (webViewState.title === 'Instagram' && webViewState.url === 
                          'https://www.instagram.com/') {
      this.setState({ key: key + 1 })
    }
... ... ...
I think the issue is related to `title` and `webViewState.url`.
As I checked the title and url when load instagram page, the title was 'Login Instagram' and the url was `"https://api.instagram.com/oauth/authorize/?client_id=XXXXX&redirect_uri=XXXXX&response_type=token"`.
So the key hadn't changed.
I hope you please check the code and if this is a bug, please fix asap.
Thank you and regards.
![insta1](https://user-images.githubusercontent.com/31640360/59703673-fd748900-922c-11e9-95a0-fa9e4c9c02b2.png)
![insta2](https://user-images.githubusercontent.com/31640360/59703880-707dff80-922d-11e9-958c-5c03799d30e8.png)

**Comment by hungdev** [comment]
@jinguohao1991 To login with another account, you must clear cookies before login another account.
Please read:
https://github.com/hungdev/react-native-instagram-login#logout

**Comment by hungdev** [comment]
@jinguohao1991 Feel free to let me know if you cant resolve your problem.

**Comment by jinguohao1991** [comment]
Thank you for your reply.
I have still the same issue.
I have installed "react-native-cookies": "^3.3.0", and linked to iOS manually.
This is my code for opening Instagram Login modal
=========
const onInstaLoginClick = () => {
      CookieManager.clearAll().then(() => {
        this.setState({ token: null })
      });
      this.instagramLogin.show();
    };
===========
The instagram still logs in with previous Account automatically.
So I cannot use another account.

**Comment by jinguohao1991** [comment]
I have tried your example with your video.
Here is my recorded video.
https://www.youtube.com/watch?v=6W-RVOUFLqE&feature=youtu.be
Thank you.

**Comment by IcebergRage** [comment]
Hello, I have the same issue.
Do you have any solution ?

**Comment by IcebergRage** [comment]
I found :
Add this in Webview 
```
cacheEnabled={false}
incognito={true}
thirdPartyCookiesEnabled={false}
sharedCookiesEnabled={false}
domStorageEnabled={false}
```

I will do a PR soon

**Comment by jinguohao1991** [comment]
Hi, @IcebergRage. Thank you.
If I test with https://github.com/hungdev/react-native-instagram-login/tree/master/Example, where to put this code?
Inside this package directly or inside my code?
Hope your update.

**Comment by hungdev** [comment]
@jinguohao1991 @IcebergRage I know the reason. Due to the cookies library is not working and I'm trying to find a way to help you.
read more:
https://github.com/joeferraro/react-native-cookies/issues/78
currently, solution is disable cookies, but in some cases when logging back, we need to keep cookies, and users don't need to log in again.
So i still recommend use clear cookies when logout.
@jinguohao1991 here is code for you:

```jsx
        <InstagramLogin
          ref={ref => this.instagramRef = ref}
          clientId='************'
          redirectUrl='https://google.com'
          scopes={['public_content+follower_list']}
          onLoginSuccess={(token) => this.setState({ token })}
          onLoginFailure={(data) => this.setState({ failure: data })}
          cacheEnabled={false}
          incognito={true}
          thirdPartyCookiesEnabled={false}
          sharedCookiesEnabled={false}
          domStorageEnabled={false}
        />
```

**Comment by jinguohao1991** [comment]
> @jinguohao1991 @IcebergRage I know the reason. Due to the cookies library is not working and I'm trying to find a way to help you.
> read more:
> [joeferraro/react-native-cookies#78](https://github.com/joeferraro/react-native-cookies/issues/78)
> [joeferraro/react-native-cookies#127](https://github.com/joeferraro/react-native-cookies/issues/127)
> currently, temporary solution is disable cookies, but in some cases when logging back, we need to keep cookies, and users don't need to log in again.
> So i still recommend persist cookies and clear cookies when logout.
> We can try with another library manage cookies.
> @jinguohao1991 here is code for you:
> 
> ```js-jsx
>         <InstagramLogin
>           ref={ref => this.instagramRef = ref}
>           clientId='************'
>           redirectUrl='************'
>           scopes={['basic']}
>           onLoginSuccess={(token) => this.setState({ token })}
>           onLoginFailure={(data) => this.setState({ failure: data })}
>           cacheEnabled={false}
>           incognito={true}
>           thirdPartyCookiesEnabled={false}
>           sharedCookiesEnabled={false}
>           domStorageEnabled={false}
>         />
> ```

This works perfectly for me.
<InstagramLogin
          ref={ref => this.instagramRef = ref}
          clientId='************'
          redirectUrl='************'
          scopes={['basic']}
          onLoginSuccess={(token) => this.setState({ token })}
          onLoginFailure={(data) => this.setState({ failure: data })}
          cacheEnabled={false}
          useWebKit={true}
          sharedCookiesEnabled={true}
        />
