### ISSUE TITLE
Random error loading login page "too many HTTP redirects"

### ISSUE THREAD

**Issue by bscaspar** [hungdev/react-native-instagram-login#38]
Most of the time this works great! However, occasionally I receive the following error when the modal appears:
```
Error loading page
Domain: NSURLErrorDomain
Error Code: -1007
Description: too many HTTP redirects
```
I am on version 1.0.8.

This error clears after reloading the app and waiting a bit. Overall not a good experience for our users though.
![IMG_4661](https://user-images.githubusercontent.com/6042704/60629625-4e4abc80-9dab-11e9-9af7-b9b397c7baf1.jpeg)

**Comment by hungdev** [comment]
@bscaspar please update to latest version. `v1.1.1`.
Let me know if it stills error after the update.

**Comment by bscaspar** [comment]
I can't update to v1.1.1 since this is an un-ejected expo app. I was able to update to v1.1.0, would that potentially resolve the issue?

**Comment by hungdev** [comment]
@bscaspar please read [this comment](https://github.com/hungdev/react-native-instagram-login/issues/29)

**Comment by bscaspar** [comment]
Hey @hungdev I saw that comment and I upgraded to v1.1.0. Will this resolve the login issue I am seeing?

**Comment by hungdev** [comment]
@bscaspar yes, but you must add www in redirectUrl ( both redirectUrl props and https://www.instagram.com/developer/clients/)

**Comment by bscaspar** [comment]
@hungdev I upgraded and changed both URLs, however some users are still seeing this problem.

**Comment by hungdev** [comment]
I updated to new version. This topic should be closed. Feel free to open. :)
