### ISSUE TITLE
Scope error when logging in

### ISSUE THREAD

**Issue by jacobogart** [hungdev/react-native-instagram-login#41]
Error Received: 
```{“error_type”: “OAuthException”, “code”: 400, “error_message”: “Invalid scope field(s): public_content”}```

Solution: Change scope from "public_content" to "basic"

**Comment by hungdev** [comment]
Sorry, recently im so busy. so i dont have much time to check issues. thanks you so much. @jacobogart

**Comment by zaakzaku** [comment]
Please fix it.

**Comment by hungdev** [comment]
@zaakzaku  It has been merged, you can install with command:
`npm i -s https://github.com/hungdev/react-native-instagram-login.git`
I am trying to fix other errors before making a new version.
