### ISSUE TITLE
iOS Deprecated API UIWebView

### ISSUE THREAD

**Issue by NewBieBR** [hungdev/react-native-instagram-login#43]
Hi, 

I got this message from Apple

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

And the issue might come from react-native-webview you're using: https://github.com/react-native-community/react-native-webview/issues/819

There might be a fix using `useWebKit={true}`, it's mentioned in that issue.

**Comment by hungdev** [comment]
@NewBieBR  thank your mentioned. i will add this props to default props, but also you can add it directly from webview props like this:
```
<InstagramLogin
        ref= {ref => this.instagramLogin= ref}
        clientId='xxxxxxxxxx'
        redirectUrl='yourRedirectUrl'
        scopes={['public_content', 'follower_list']}
        onLoginSuccess={(token) => this.setState({ token })}
        onLoginFailure={(data) => console.log(data)}
       useWebKit={true}
    />
```

**Comment by Titozzz** [comment]
react-native-webview maintainer here 👋 , you need to update the webview to 7.0.1+ to fix this. And the useWebkit has been removed since UIWebView doesn't exist anymore :)
