### ISSUE TITLE
Getting error as "requireNativeComponent:RNCWKWebView" was not found in the UI Manager

### ISSUE THREAD

**Issue by nihp** [hungdev/react-native-instagram-login#44]
I am using react-native-instagram-login in my app. I have updated the **react-native-webview to 7.0.3** after this I can't able to login the app and it shows the below error. Refer the attachment
![Screenshot 2019-09-05 at 5 16 00 PM](https://user-images.githubusercontent.com/36992338/64339304-53bdc080-d001-11e9-8e6a-394c68b762c4.png)

**Comment by marcojr** [comment]
Same here !

**Comment by hungdev** [comment]
@nihp and @marcojr 
Please linking manually. Hope links can help you.
https://github.com/react-native-community/react-native-webview#common-issues
https://github.com/react-native-community/react-native-webview/issues/235#issuecomment-452382921
https://github.com/react-native-community/react-native-webview/issues/161
Sorry i don't have much time to help you more detail.

**Comment by ThomasLech** [comment]
I resolved the issue, and provided a step-by-step solution: https://github.com/hungdev/react-native-instagram-login/issues/45

**Comment by hungdev** [comment]
@nihp @marcojr @ThomasLech new version published. It fixed this issue and updated example for react-native version > 0.6.
thanks guys. Happy weekend.
Let me know if the error still exists.
