### ISSUE TITLE
Getting "ErrorType: OAuthException" while trying to login using react-native-instagram-login

### ISSUE THREAD

**Issue by nihp** [hungdev/react-native-instagram-login#49]
I am getting the below attached error while trying to login the app using react-native-instagram-login. Refer the attached image
`
{"errorType":  "OAuthException", "code": "400", errorMessage: "InvalidScopefields: public_content, follower_list"}`
![Screenshot 2019-09-11 at 3 32 38 PM](https://user-images.githubusercontent.com/36992338/64688168-688ad000-d4a9-11e9-9c18-886acd5a009f.png)

**Comment by hungdev** [comment]
@nihp please read [example](https://github.com/hungdev/react-native-instagram-login#usage)
```
scopes={['basic']}
```

**Comment by nihp** [comment]
Thanks @hungdev . It worked for me

**Comment by khuznain** [comment]
You will need to add the Instagram test user. After that, you will be able to login and  you will need to login from the account!
