### ISSUE TITLE
Login instagram using Native Instagram app.

### ISSUE THREAD

**Issue by jinguohao1991** [hungdev/react-native-instagram-login#50]
Hi, all.
If an Instagram app was installed on the device, is there a way to open the native Instagram app and get token after login instead of using WebView page?

**Comment by gianpaj** [comment]
I don't think there's a way to do it. Tinder, for example, opens a WebView as well (tested on iOS)

**Comment by hungdev** [comment]
I don't know how, but if it is open from the Instagram app itself, I think Facebook will have to create a SDK.
