### ISSUE TITLE
Exposing secret on the client side is bad practice

### ISSUE THREAD

**Issue by fniewijk** [hungdev/react-native-instagram-login#54]
I was looking at using your package, but when I read your code and compare it with the manual it says that you should not share the app_secret client side. It suggests you should use the client side implicit authentication. [link](https://www.instagram.com/developer/authentication/)

Are you aware of this? This looks like an issue that is resolvable. The implicit authentication does not need the secret.

**Comment by gitstud** [comment]
The docs here show where to put the app secret but not where to get it, you can serve the app secret from your server and then connect it with however you manage state

**Comment by codeundercoverdev** [comment]
@gitstud @fniewijk  doesn't that still expose the app secret to the user when you fetch it from your server?

**Comment by victor871129** [comment]
> @gitstud @fniewijk doesn't that still expose the app secret to the user when you fetch it from your server?

Yes, that's why you need to check the integrity of your app with a Tampering Detection solution and only store the secret on the phone RAM

**Comment by ChrisEelmaa** [comment]
yeah, this is a bit design flaw in this lib, there should never be appSecret exposed anywhere on the JS side, memory or no memory.

quick look at the code indicates that it handles both implicit authentication as well. Just don't fill in app_secret, and ensure ```responseType="access_token"```

**Comment by hungdev** [comment]
I added an option for expose secret, [read doc here](https://github.com/hungdev/react-native-instagram-login#server-side-explicit-discuss-here)

**Comment by tgreco** [comment]
@hungdev is it possible to update the PropType appSecret to not be required so we don't see the error in the console?
Seems like doing it server side is best practice so I wouldn't expect to see an error in the console for going that route.

Appreciate the library!

**Comment by jaweherncir** [comment]
Hello please some hir con help me to get the profil photo of Facebook account with nodejs please
