### ISSUE TITLE
Invalid scope response  

### ISSUE THREAD

**Issue by knjl34** [hungdev/react-native-instagram-login#55]
hi,
when i have submit id password then json response with 'invalid scope " error!!

below code snippet 
ver 2.0.0

<InstagramLogin
                    ref={ref => (this.instagramLogin = ref)}
                    appId={config.instaAppId}
                    appSecret={config.instaappSecret}
                    redirectUrl={config.instaRedirectURL}
                    scopes={['user_profile', 'user_media']} 
                    onLoginSuccess={token => {
                      this.handleInstaLogin(token);
                      this.setState({ isLoginViaWhich: 'instagram' });
                    }}
                    onLoginFailure={data => console.log(data)}
                  />

**Comment by nihp** [comment]
@knjl34 
Can you confirm this? Are you using Instagram graph API or Instagram Basic Display API? 

From where you get appID and secretID.

What is the redirect url which needs to give a valid url or not

**Comment by knjl34** [comment]
> give

 Can you confirm this? Are you using Instagram graph API or Instagram Basic Display API?  ==> **Basic display API**

From where you get appID and secretID. => **Facebook developer console as they have merged both facebook login as well as instagram login just need to verify business profile.**

**Comment by nihp** [comment]
Thanks for your reply. 

I have another clarification.

If we use Instagram graph API, we need to send our app to App review if we moving to live mode.

Also for  Basic display API while moving to live did we need to submit the app for app review?

**Comment by knjl34** [comment]
yes app review is mandatory for using Instagram login as that one is also same process which are already available in developer.Instagram but that one is stopped so in this scenario in this case also!!

so submit for app review!
let me know if i am wrong or any other feedback/query.

**Comment by nihp** [comment]
Did you submit or pushed your app to appstore?

**Comment by knjl34** [comment]
not yet already submit for review!

but yes i have already done that in native with previous process of Instagram which is from developer.instagram right now that one deprecated so i have done with facebook.developer.com

what about you status regarding login ?

**Comment by nihp** [comment]
I not pushed for App review. Now investigating how it will be done correctly.

Okay.

Note all the steps while processing from a step to another step.

**Comment by knjl34** [comment]
hey,
you need to add apk/ipa and video as well as deauth url then the submission will complete.

**Comment by nihp** [comment]
Okay

**Comment by knjl34** [comment]
AS of now closed
