### ISSUE TITLE
Getting "ErrorType: OAuthException" while trying to login using react-native-instagram-login

### ISSUE THREAD

**Issue by nihp** [hungdev/react-native-instagram-login#57]
I am getting "ErrorType: OAuthException" while trying to login using react-native-instagram-login
![Screenshot 2019-12-05 at 10 34 21 AM](https://user-images.githubusercontent.com/36992338/70215190-f140a180-1762-11ea-9694-32de2479944f.png)

**Comment by nihp** [comment]
@hungdev Could you please look into this?

**Comment by hungdev** [comment]
@nihp please fill correct Instagram App ID and Instagram App Secret as my image guide.

**Comment by nihp** [comment]
Shall I need to add scope as basic or  scopes={['user_profile', 'user_media']}

I gave the AppId and App secret as you mentioned there. Still facing the same.


My Code

`  <InstagramLogin ref={ref => (this.instagramLogin = ref)} scopes={['user_media']}  redirectUrl='my url' appId='appid' appSecret = 'appSecret' onLoginSuccess={(token, result) => this.socialLogin(token, 2)} onLoginFailure={(data) => this.setState({failure: data})}/>`

**Comment by nihp** [comment]
Now I am getting 
If I change to basic I am getting an Oops, an error occurred

 Also while change the scopes={['user_profile', 'user_media']} now I am getting an error message "Insufficient developer role"

![Screenshot 2019-12-12 at 2 08 00 PM](https://user-images.githubusercontent.com/36992338/70696005-d46b1780-1ce8-11ea-9206-5e7ffcfccd69.png)

**Comment by nihp** [comment]
Now I am getting 
If I change to basic I am getting an Oops, an error occurred

 Also while change the scopes={['user_profile', 'user_media']} now I am getting an error message "Insufficient developer role"

![Screenshot 2019-12-12 at 2 08 00 PM](https://user-images.githubusercontent.com/36992338/70696005-d46b1780-1ce8-11ea-9206-5e7ffcfccd69.png)

**Comment by hungdev** [comment]
Go to Roles > Instagram Users and add your Instagram account. Then go to https://www.instagram.com/accounts/manage_access/ to accept the Tester Invite from your app.

**Comment by nihp** [comment]
In where the roles are available. In facebook developer account or
instagram developer account

**Comment by nihp** [comment]
Thanks the above error gone

**Comment by nihp** [comment]
Can you confirm that for how long the acces_token will not expired. 

Before this the access token not expired for long time. But now I am getting different access token for each time. 

Also, I am getting userId now.

Shall I need to change in server side.

**Comment by CVRamana** [comment]
> Go to Roles > Instagram Users and add your Instagram account. Then go to https://www.instagram.com/accounts/manage_access/ to accept the Tester Invite from your app.

still getting the same error

**Comment by gwendall** [comment]
Go to live mode for your facebook app

**Comment by hungdev** [comment]
please create new issue if you get the bug. This topic should be closed. Feel free to open. :)
