### ISSUE TITLE
Change language of the webview

### ISSUE THREAD

**Issue by Thomsath** [hungdev/react-native-instagram-login#69]
Hi,

I'm asking myself if we can change the language of the instagram webview (like put it in french). I'm trying to add ?hl=fr in the link, but it doesn't work. That could be cool to manage from the component. Any idea ? Is it possible ? 

Thanks

**Comment by goxr3plus** [comment]
I agree :) , the development of this library seems dead though.

**Comment by AmirDoreh** [comment]
[pr for this issue has been created](https://github.com/hungdev/react-native-instagram-login/pull/93)

@hungdev
