### ISSUE TITLE
Question about instagram auth limitations

### ISSUE THREAD

**Issue by belgamo** [hungdev/react-native-instagram-login#71]
I was reading the guides of facebook API and I came across this warning. In development it works, but will it work on production?

![image](https://user-images.githubusercontent.com/19699724/84188264-b731be80-aa69-11ea-96ba-7abff183e3f6.png)

**Comment by tgreco** [comment]
What was the answer to your question @belgamo?

**Comment by belgamo** [comment]
Yeah, I was right. The Facebook politics doesn't allow the authentication flow via Instagram and you should use the Facebook auth tool instead.
