### ISSUE TITLE
Cannot login with the new API

### ISSUE THREAD

**Issue by IronTony** [hungdev/react-native-instagram-login#72]
Hi and thank you for the package.
I have upgraded to the laster one and started to use the new IG Login API, but I have problem in the process.
I went to the `developer.facebook.com`, `Instagram section -> Basic Display`, filled in all the info in page, added a test user and accepted the invitation, copied/pasted the `ID app Instagram` and `Secret` in the part of the code of your package, but when I try to login with the test user I have this error:
![image](https://user-images.githubusercontent.com/3645225/84629998-84fde200-aeeb-11ea-97e3-37922031094c.png)

Thank you in advance

**Comment by hungdev** [comment]
i think you are wrong some fields. Please check it and correct it. If it still gets error. I will create video guide for you. :)

**Comment by yasirwahid** [comment]
@hungdev adding tester is important? i have performed every step but my onLoginFailure function is running without errors . instead of onLoginSuccess

**Comment by hungdev** [comment]
@yasirwahid yup, adding tester is important.

**Comment by IronTony** [comment]
@hungdev Unfortunately I retried and checked the config but with no luck. Always the same problem

**Comment by IronTony** [comment]
Everything works. Dunno what happened
