### ISSUE TITLE
Invalid Scope error when login ?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [hungdev/react-native-instagram-login#73]
HI,

I have do the below code for instagram login, but there is invalid scope : [] issue, Can you help me what's reason ?

```
<InstagramLogin
        ref={ref => (this.instagramLogin = ref)}
        appId='816051862258833'
        appSecret='fb45c046f8903c06fe38648f805ce3333333'
        redirectUrl='https://apple.com/services'
        scopes={['user_profile', 'user_media']}
        onLoginSuccess={(data) => console.log("****** Success", data)}
        onLoginFailure={(data) => console.log("******FAIL", data)}
      />
```

![Screenshot 2020-06-23 at 11 16 13 AM](https://user-images.githubusercontent.com/17870723/85365583-47c8ce00-b543-11ea-83f1-0a2c322c8b41.png)

Please help me.

**Comment by hungdev** [comment]
try adding scope in https://developers.facebook.com/
like this: 
![image](https://user-images.githubusercontent.com/12009276/85654358-63191200-b6d8-11ea-892b-18c829a8eafd.png)

**Comment by hungdev** [comment]
if you still get the error, feel free to open.

**Comment by alapanerao** [comment]
I am getting this same error when i try login with Facebook.
