### ISSUE TITLE
invalid redirect url

### ISSUE THREAD

**Issue by aftabaminzoobiapps** [hungdev/react-native-instagram-login#77]
i give an invalid redirect url.  how can i give redirect url so it will work.

**Comment by ashmaster** [comment]
> i give an invalid redirect url. how can i give redirect url so it will work.

Did you figure it out ? I am also getting this problem

**Comment by hungdev** [comment]
you have to fill correct redirect url like fb dev console in this field: `Valid OAuth Redirect URIs`  like this
![image](https://user-images.githubusercontent.com/12009276/98137518-a8561780-1ef4-11eb-843d-3cd6f2d03502.png)

**Comment by hungdev** [comment]
Feel free to open if you still get this problem.

**Comment by aftabaminzoobiapps** [comment]
> > i give an invalid redirect url. how can i give redirect url so it will work.
> 
> Did you figure it out ? I am also getting this problem

yes, you have to give. www.googel.com/
