### ISSUE TITLE
Documentation has incorrect params

### ISSUE THREAD

**Issue by tgreco** [hungdev/react-native-instagram-login#79]
The documentation to convert the code to an access_token has it listed as app_id and app_secret.
It's actually client_id and client_secret.

![image](https://user-images.githubusercontent.com/27317898/96369049-52742800-111d-11eb-9887-77e3ba804f64.png)

**Comment by hungdev** [comment]
I know that, but It seems to be able to use app_id and app_secret

**Comment by hungdev** [comment]
I updated docs, thank you so much. I love your report.
