### ISSUE TITLE
Redirect uri not matches?

### ISSUE THREAD

**Issue by soikatesc** [hungdev/react-native-instagram-login#8]
# What would be the redirect uri?

 On instagram when I tried to register a ne
![oauth_exce](https://user-images.githubusercontent.com/24787023/35250823-8407ad46-ffa6-11e7-99e4-214d538833b9.png)
w client it ask me to enter redirect uri.

**Comment by reactionic127** [comment]
I am getting same issue.

**Comment by hungdev** [comment]
sorry I'm late. last week i'm busy.
Your website url must be same when registering sandbox client api on instagram https://www.instagram.com/developer/
here we used website url: https://google.com Valid redirect URIs: https://google.com
<img width="1309" alt="screen shot 2018-01-31 at 7 58 27 pm" src="https://user-images.githubusercontent.com/12009276/35624298-30179f30-06c1-11e8-8e87-36f9c432face.png">

**Comment by reactionic127** [comment]
Thanks for your response.
In my case, I added the matched redirect URI on frontend code.
It works well on my side.
Regards.

**Comment by sabirbasha** [comment]
Am getting same issue i have tried with all the suggestions still am getting same Error. Could you any one please help to resolve the issue
