### ISSUE TITLE
WebView error: Invalid plateform app

### ISSUE THREAD

**Issue by KeyurVaghani** [hungdev/react-native-instagram-login#85]
In android, Webview is showing error after login into instagram. ![20210304_155306.jpg](https://user-images.githubusercontent.com/33790237/109949750-bdf01800-7d01-11eb-98af-929e8dcbf198.jpg)

**Comment by geniecoder** [comment]
@KeyurVaghani did you found any solution?

**Comment by hungdev** [comment]
I tried it again, it works fine

**Comment by hungdev** [comment]
i created a video for new guys
https://www.youtube.com/watch?v=Xw-mCiyUMgE
feel free to open if it still gets errors
