### ISSUE TITLE
Invalid scope [ ] error

### ISSUE THREAD

**Issue by jaySoni9292** [hungdev/react-native-instagram-login#90]
Getting issue {"error_type":"OAuthException","code":"400,"error_message":"Invalid scope :[ ]"}

**Comment by toonTheta** [comment]
I got the same error...

**Comment by hungdev** [comment]
what is your scope? I tried it again, it works fine.

**Comment by toonTheta** [comment]
I resolved this by activating the App testing the Instagram 
https://www.instagram.com/accounts/manage_access/

**Comment by hungdev** [comment]
i created a video for new guys
https://www.youtube.com/watch?v=Xw-mCiyUMgE
